import { Column, Entity, PrimaryGeneratedColumn, OneToOne, JoinColumn } from 'typeorm';
import { User } from './userModel';
import { Scooter } from './scooterModel';

@Entity()
export class Event {
    @PrimaryGeneratedColumn() // autogenerated
    id: number;

    @Column({
        length: 100,
    })
    name: string;

    @Column()
    startDate: string;

    @Column()
    endDate: string;

    @OneToOne(() => User)
    @JoinColumn()
    user: User;

    @OneToOne(() => Scooter)
    @JoinColumn()
    scooter: Scooter;
}
