import { Column, Entity, PrimaryGeneratedColumn, BaseEntity, OneToMany, JoinColumn } from 'typeorm';
import { Event } from './eventModel';

@Entity()
export class Scooter extends BaseEntity {
    @PrimaryGeneratedColumn() // autogenerated
    id: number;

    @Column({
        length: 100,
    })
    name: string;

    @Column({
        length: 100,
    })
    model: string;

    @Column({
        length: 100,
    })
    status: string;

    @OneToMany(() => Event, event => event.scooter)
    @JoinColumn()
    event: Event;
}
