import { BaseEntity, Column, Entity, PrimaryGeneratedColumn } from 'typeorm';

@Entity()
export class User extends BaseEntity {
    @PrimaryGeneratedColumn() // autogenerated
    id: number;

    @Column({
        length: 100,
    })
    name: string;
}
