import { Column, Entity, PrimaryGeneratedColumn } from 'typeorm';

@Entity()
export class User {
    @PrimaryGeneratedColumn() // autogenerated
    id: number;

    @Column({
        length: 100,
    })
    name: string;
}
