import { BaseEntity, Column, Entity, JoinColumn, OneToMany, PrimaryGeneratedColumn } from 'typeorm';
import { Event } from './eventModel';

@Entity()
export class User extends BaseEntity {
    @PrimaryGeneratedColumn() // autogenerated
    id: number;

    @Column({
        length: 100,
    })
    name: string;

    // role  ( admin/user  )

    @OneToMany(() => Event, event => event.user)
    @JoinColumn()
    event: Event;
}
